title: Your awesome title
author:
  name: GitHub User
  email: your-email@domain.com
description: >
  Write an awesome description for your new site here. You can edit this line in
  _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
show_excerpts: false
minima:
  date_format: '%b %-d, %Y'
  social_links:
    twitter: jekyllrb
    github: jekyll
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
baseurl: ''
url: ''
